# Generated by Django 3.2.4 on 2022-02-26 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(blank=True, max_length=170, null=True)),
                ('numero_pagina', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app.tipologia')),
                ('descricao', models.CharField(default='', max_length=3000, null=True)),
                ('data', models.DateField()),
                ('arquivo', models.FileField(upload_to='uploads/%Y/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
