# Generated by Django 3.2.4 on 2021-11-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documenmto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=520, null=True)),
                ('instituicao', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('ano', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('autor', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('resumo', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('palavras_chaves', models.CharField(blank=True, default='', max_length=350, null=True)),
                ('categoria', models.CharField(choices=[('Saúde', 'Saúde'), ('Ciência', 'Ciência'), ('Biológia', 'Biológia'), ('Cultura', 'Cultura')], max_length=120)),
                ('tipo', models.CharField(choices=[('Artigo', 'Artigo'), ('Livro', 'Livro'), ('Palestra', 'Palestra'), ('Monografia', 'Monografia'), ('Dissertação', 'Dissertação')], max_length=100)),
                ('editora', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('orientador', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('uri', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('tipo_acesso', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('data_publicacao', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
