# Generated by Django 3.2.4 on 2021-11-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenmto',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/%Y/'),
        ),
    ]
