# Generated by Django 3.2.4 on 2021-11-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_documenmto_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenmto',
            name='uri',
            field=models.URLField(blank=True, default='', max_length=300, null=True),
        ),
    ]
