# Generated by Django 3.2.4 on 2021-11-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_alter_documenmto_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenmto',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/'),
        ),
        migrations.AlterField(
            model_name='documenmto',
            name='resumo',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
